version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - freelance-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - freelance-redis:/var/lib/redis/data

  freelance_backend:
    build:
      context: .
      #args:
      #  USER_ID: "${USER_ID:-1000}"
      #  GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./drkiq:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      #args:
      #  USER_ID: "${USER_ID:-1000}"
      #  GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - freelance_backend
    ports:
      - '8020:8020'

volumes:
  freelance-postgres:
  freelance-redis:
